In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [9]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(shape=(20,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
type(0)

int

In [16]:
type(0.)

float

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.random.seed(101)
arr= np.random.randint(0,100,10)

In [22]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [23]:
arr2 = np.random.randint(0,100,10)

In [24]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [25]:
arr.max()

95

In [26]:
arr.argmax()

0

In [27]:
arr.min()

9

In [28]:
arr.argmin()

7

In [29]:
arr.mean()

60.8

In [34]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [36]:
mat = np.arange(0,100).reshape(10,10)

In [38]:
mat.shape

(10, 10)

In [47]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [40]:
row = 0
co = 1

In [44]:
mat[row,co]

1

In [45]:
mat[4,6]

46

In [46]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [51]:
mat[0:3,0:4] = 0

In [53]:
mynewmat = mat.copy()

mynewmat[ 

In [54]:
mynewmat[0:6,:]=999

In [55]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])